site_name: RemoteRabbit dot/config files docs
site_url: https://remoterabbit.github.io/dot_files
site_author: RemoteRabbit
site_description: A site to host some documenation on why and how I use my dot/config files
theme:
  name: terminal
  palette: dark
  features:
    - navigation.side.indexes

nav:
  - Home: index.md
  - .config:
      - Index: 'config/index.md'
      - Neovim:
        - Index: 'config/neovim/index.md'
        - Config: 'config/neovim/config.md'
        - plugins: 'config/neovim/plugins.md'
